---
output: pdf_document
---


# Introduction

## Dataset Description

### VFINX - S&P 500 Index Fund

The Vanguard 500 Index Fund ^[@VFINX:TheVanguardGroup:2016] (VFINX) is an exchange traded fund (ETF) that invests in 500 of the largest U.S. companies. These companies span many different industries, and thus provides investors with full exposure to the domestic stock market. The fund focuses on large-capitalization companies that encompass nearly 75% of the U.S. equity market. The fund treats the Standard & Poor's 500 ^[@SP500:SPDowJones:2016] as its benchmark, and thus acts as a measurement of overall stock market performance.

### VEURX - European Stock Index Fund

The Vanguard European Stock Index Fund ^[@VEURX:TheVanguardGroup:2016] (VEURX) is an ETF that provides investors with exposure to the major stock markets of Europe. The fund holds positions in approximately 1,200 securities across European markets, which represents nearly half of global (non U.S.) equity. In addition to systematic risk, this fund is also exposed to currency risk, and may have significant regional risk as all markets in which the fund invests in are located in Europe. This fund treated the MSCI Europe Index ^[@EuropeIndex:MSCI:2016] as its benchmark through March 26, 2013, but has used the FTSE Developed Europe Index ^[@DevelopedEuropeIndex:FTSE:2016] as its benchmark thereafter.

### VEIEX - Emerging Markets Index Fund

The Vanguard Emerging Markets Stock Index Fund ^[@VEIEX:TheVanguardGroup:2016] (VEIEX) is an ETF that provides investors with exposure to emerging markets around the world including but not limited to: Brazil, Russia, India and China. As emerging markets tend to be more volatile, this fund has the potential for higher returns, but with considerably higher risk. Similar to the European Stock Index Fund, the returns of this fund too are exposed to significant currency risk. This fund treated the FTSE Emerging Index ^[@EmergingIndex:FTSE:2016] as its benchmark through November 2, 2015, but has since switched to the FTSE Emerging Markets All Cap China A Transition Index. ^[@EmergingAllCapIndex:FTSE:2016]

### VBLTX - Long-Term Bond Index Fund

The Vanguard Long-Term Bond Index Fund ^[@VBLTX:TheVanguardGroup:2016] (VBLTX) is an ETF that provides investors with exposure to long-term bond (i.e. debt obligation) investments. This fund holds positions in both corporate and U.S. Government bonds with a maturity of 10 years or more. However, due to the fact that long-term bonds are highly exposed to price fluctuations caused by changing interest rate, which is attributable to the high duration and convexity of the underlying long-term bonds. This fund used the Barclays U.S. Long Government Float Adjusted Index ^[@LongGovernmentIndex:BarclaysBankPLC:2015] as its bechmark through December 31, 2009, but has since swithced to the Barclays U.S. Long Government/Credit Float Adjusted Index. ^[@LongGovernmentCreditIndex:BarclaysBankPLC:2015]

### VBISX - Short-Term Bond Index Fund

The Vanguard Short-Term Bond Index Fund ^[@VBISX:TheVanguardGroup:2016] (VBISX) is an ETF that provides investors with exposure to a diversified portoflio of short-term bonds (i.e. debt obligations). This fund holds positions in both corporate and U.S. Government short-term bonds with maturities of 1 to 5 years. Due to the fact that short-term bonds have low duration and convexity, investors can expect minimal price movement with relation to interest rates from this fund, and thus lower yield. This fund uses the Barclays U.S. Government/Credit Float Adjusted 1-5 Year Index ^[@1to5YearGovernmentCreditIndex:BarclaysBankPLC:2015] as its benchmark.

### VPACX - Pacific Stock Index Fund

The Vanguard Pacific Stock Index Fund ^[@VPACX:TheVanguardGroup:2016] (VPACX) is an ETF that provides investors with exposure to a diversified portfolio of securities in markets of developed nations in the Pacific region. The fund holds positions in over 2,000 securities across the Pacific, with the bulk of them being located in Japan. This investment pool represents approximately a quarter of the global (non U.S.) equity market capitalization. The fund initially used the MSCI Pacific Index ^[@PacificIndex:MSCI:2016] as its benchmark until March 26, 2013, before switching to the FTSE Developed Asia Pacific Index ^[@DevelopedAsiaPacificIndex:FTSE:2016] through September 30, 2015, until finally switching to the FTSE Developed Asia Pacific All Cap Index ^[@DevelopedAsiaPacificAllCapIndex:FTSE:2016], which is uses today.


## ETF Historical Prices

```{r time_plot_price, fig.cap = figures("time_plot_price")}
figures.add(name = "time_plot_price", caption = "Timeplot of ETF prices")
plot(prices, xlab = "Time", panel = panel.time.plots.dates, col = asset.colors, main = "")
```

Analyzing the price data each of the ETFs in `r figures.cite("time_plot_price")`, it is clear that VFINX and VBISX have the most stable stream of returns, which is reflected in the (relatively) steady increase in their respective prices over time. Furthermore, it is apparent from the visible trend of each of the ETF prices that while specific, small-scale fluctuations appear to be random, there are many longer time-horizon trends that are common across all of the funds.

In the case of VFINX, the constant positive progression of the price is to be expected as the stock market has displayed an above-average yearly growth rate over the time horizon considered in the graph. This above-average growth rate is explained by renewed investor confidence in the market in the aftermath of the financial crisis of 2009. Considering the VBISX ETF, which tracks the prices of diversified short-term debt obligations, the price increase can be attributed to a constant reduction in interest rates (yield) of short-term debt in the last five years.^[@ShortTermInterestRates:OECD:2016] The reducing interest rates has a positive effect on the net present value (i.e. price) of the debt, which is reflected in the rising price of the VBISX ETF.

In addition to the price trends inherent to each security, the time plots also indicate that there are significant fluctuations in the prices common to all of the equity ETFs (i.e. except VBLTX and VBISX, which are debt ETFs). These common fluctuations are triggered by specific macroeconomic events, and illustrate congenial non-diversifiable risk (i.e. market risk) in each of the equity ETFs.

During the middle months of 2012, many European Union (EU) nations (Greece, Spain, Ireland, etc.) were in serious risk of defaulting (or in the case of Greece, already defaulted) on their debt obligations.^[@EuropePanicSelling:Guardian:2012] This caused a significant reduction in investor confidence in capital markets across the globe, which eventually led to massive selloffs in markets across the world, with investors shifting capital from equity investments to perceptively safer and less-risky debt investments.^[@LowTreasuryNoteYield:CNN:2012] These macroeconomic events are the cause of the simlultaneous significant reduction in equity ETF prices that track multiple regions across the world. This loss in confidence affected markets that have perceptively higher levels of risk compared to others, as is reflected by the sharper drop in emerging markets (VEIEX) when compared to less risky markets such as that of the U.S. (VBLTX). As investors shifted capital to less-risky investments, the surge in invested capital in bond markets caused a drop in bond yields, which was seen in both short-term and long-term bonds. This reduction in bond yields is reflected in the rise in the price of debt ETFs VBLTX and VBISX, as bond yields correlate negatively with the present value (i.e. price) of bonds.

Consider the stock market correction in August 2011, which rattled equity markets worldwide. Investor confidence was damaged when Greece became the first advanced economy to ever default on an International Monetary Fund (IMF) loan payment in July.^[@GreeceIMFDefault:WSJ:2015] This was followed by a surprise devaluation of the Chinese Yuan by the Government of China in August,^[@ChinaYuanDevaluation:Bloomberg:2015] which led to a large drop in the value of companies that use the Chinese Yuan as their primary currency due to their high exposure to foreign exchange risk. Significantly lowered investor confidence, coupled with indicators that the market was inflated led to an eventual global sell-off and inevitable stock market correction in August 2015.^[@BlackMonday:NYT:2015] This is reflected in the sharp drop in prices of ETFs that track regions across the globe. As with the EU credit crisis of 2012, markets that traditionally display higher levels of risk experienced the largest declines in price, as reflected by steeper drops in Emerging and Pacific Market ETFs (VEIEX and VPACX) compared to American and European Market ETFs (VFINX and VEURX).


## Types of Investment Risk

The presence of market-wide trends is extremely important in the construction of portfolios that comprise ETFs that inherently exhibit these trends. Logically, it can be deduced that trends in the price of a specific ETF that are not common across all other ETFs are attributable to some characteristic of that particular fund, which are fundamentally different from trends that emanate across all of the funds in the market.

Simply put, price trends and fluctuations are illustrations of risk perceived by investors, as a given price reflects the amount of risk an investor is willing to undertake to realize a certain return. This concept can be generalized to the different types of price fluctuations, and would have the following implications:

- Price fluctuations and trends that are specific to a given ETF are an expression of a certain risk factor that is inherent to that particular ETF
- Price fluctuations and trends that are visible across all ETFs are an expression of risk that is perpetuated across the entire market in which the ETFs operate, and is thus not specific to any given ETF

In financial theory, these two types of risk are referred to as diversifiable or unique risk, which is risk that is attributable to some characteristic of a particular ETF, and market or idiosyncratic risk, which is perceived across all ETFs in the market. The main result of this distinction is that combinations of ETFs with particular levels of diversifiable risk can be combined to eliminate their effect, leaving only the idiosyncratic risk of the market, which achieving an enhanced rate of return compared to that of the market as a whole. This is the ideal output of a portfolio, and its realization is the ultimate goal that motivates modern Portfolio Construction Theory.
