---
output: pdf_document
---

# Value at Risk

## Introduction

The concept of *Value at Risk*, or VaR is derived from the reality that in conducting statistical analysis, returns from an asset are treated as a sample from a larger population, which in turn has an observable distribution. Thus, using statistical inference about the positional and scaling parameters for a given security, it is possible to assign probabilities to each return prospect, whithin the bounds of estimation. Similarly, it is also possible to derive the return that is expected to occur at a certain probability.

The VaR quantifies this measure, by attaching a dollar value to the potential losses at a given probability. That is, the 1% VaR would indicate - given the past performance of the sample and value of the initial investment - how much money an investor could expect to lose in the subsequent period, with a probability of 0.01 or 1%. This concept is extremely central to modern finance, as better estimation tools increase the reliability of these measures, and provides a metric by which real-world losses can be gauged, which is sometimes more useful than perhaps citing the standard deviation of a distribution when attempting to illustrate risk.


## ETF Value at Risk

Displayed in `r tables.cite("asset_var_01")` and `r tables.cite("asset_var_05")` are the monthly VaRs for each of the ETFs at the 1% and 5% level, calculated using the implied normal distribution quantiles and given an initial investment of \$`r formatC(w0, big.mark = ',', format = 'd')`. Monthly VaRs are also determined using the emperical quantiles of each of the samples, which are calculated from the distribution of the sample, rather than from an assumed distribution. Also displayed are the annual VaRs, calculated using the annualized expected returns and standard deviations of each of the ETFs. Additionally, 95% confidence intervals and standard errors of estimation were determined using the bootstrap method, discussed in the previous section. These estimates can be analyzed to develop a better insight into the behavior of the effect of extreme returns on an actual investment in the ETFs.

Consider VEIEX, which has the highest estimated VaR at both the 1% and 5% level, over both monthly and annual time horizons. The relatively high disparity observed between the annualized and emperical VaRs can be attributed to the fact that the distribution of the sample VEIEX returns had smaller tails (i.e. positive excess kurtosis) than those assumed by the normal distribution, which is reflected in the lower estimates for VaR determined with emperical quantiles as opposed to normal quantiles.

On the other hand, VBISX exhibits the lowest VaRs for both levels, across both time horizons. This is to be expected, as it was the ETF that had the lowest variability of returns, and would thus have a higher expected return compared to its mean at the tails of its distribution.

```{r etf_var}
tables.add(name = "asset_var_01", caption = "1% Value at Risk Analysis for each ETF (Key: A: Analytical Normal, E - Emperical, B - Bootstrap)")
tables.add(name = "asset_var_05", caption = "5% Value at Risk Analysis for each ETF (Key: A: Analytical Normal, E - Emperical, B - Bootstrap)")
kable(asset.var.01.table, caption = tables("asset_var_01"), digits = 2)
kable(asset.var.05.table, caption = tables("asset_var_05"), digits = 2)
```

Furthermore, considering the estimation standard error calculated for each of the VaR, it is clear that despite these numbers add a sense of realism to possible returns from the assets, they are in fact estimates, and have high levels of variability. This is reflected in the 95% confidence intervals, where in some cases such as the 95% CI for 5% VaR for VEURX and VEIEX come in close proximity to the correspinding 1% VaR.

While it may seem that the differences between the annual and monthly VaRs are extremely small, this is to be expected. It is due to the fact that unlike the annualized returns of the ETFs, VaR does not scale linearly, as it is an exponential of the affine combination of the expected return and standard deviation of the assets. Recall, the expected return is scaled by a factor of $12$, while the standard deviation is scaled by a factor of $\sqrt{12}$. This illustrates yet again the importance of the precision, and assumed time invariance of these estimates, as small changes may have a large effect on measures such as the VaR. Considerng the annual VaR in particular, an increase in the variance of returns over the course of a year would not be reflected in the monthly statistics, and thus not reflected in the annualized monthly statistics which may lead to a gross misestimation of metrics such as the yearly VaR.

The large confidence intervals and standard errors of estimation can be attributed to the fact that the VaR is calculated using the location and scale parameters of the samples, which too have high levels of variability associated with them, as discussed earlier in the report. Thus, while the implications of VaR should indeed be taken into consideration when making investmnet decisions, the fact that it too is an estimate, derived from an estimate means that VaR should not be the only factor that is analyzed.
